name: Create Release
run-name: ${{ github.actor }} creates release on ${{ github.ref_name }} with ${{ github.event_name }} ðŸš€

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check target branch
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
          exit 1

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Gather release information
        run: |
          SEMVER_REGEX='^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$'

          # Extract version number
          VERSION=$(git log -1 --pretty=format:"%b" | sed -E 's/^[Rr]elease\///' | sed 's/ /-/g')

          # Validate tag based on SemVer
          if [[ "$VERSION" =~ $SEMVER_REGEX ]]; then
            echo "Valid SemVer: $VERSION"
          else
            echo "Invalid SemVer: $VERSION"
            exit 1
          fi

          # Extract major version
          MAJOR=$(echo "$VERSION" | cut -d. -f1)

          # Check if release is in a prod or pre state?
          if [[ "$MAJOR" != "0" && "$VERSION" != *-* ]]; then
            IS_PROD_RELEASE="true"
            IS_PRE_RELEASE="false"
          else
            IS_PROD_RELEASE="false"
            IS_PRE_RELEASE="true"
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IS_PRE_RELEASE=$IS_PRE_RELEASE" >> $GITHUB_ENV
          echo "IS_PROD_RELEASE=$IS_PROD_RELEASE" >> $GITHUB_ENV

          echo "Version: $VERSION"
          echo "Pre-release?: $IS_PRE_RELEASE"
          echo "Prod-release?: $IS_PROD_RELEASE"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          prerelease: ${{ env.IS_PRE_RELEASE }}
          generate_release_notes: true
          make_latest: ${{ env.IS_PROD_RELEASE }}
